"""Per-instruction trace of the Zelda cave-bug window.

Loads cold-boot Rev A, replays zelda_start_419 to frame 1465 (just
before the Start-press explosion at frame 1466), then steps the
emulator one CPU instruction at a time for the next ~30 frames,
logging every instruction's trace line.

Output: `/tmp/zelda_cave_trace.txt` — one line per CPU instruction in
the bug window. Each line is the canonical nestest trace format:

    PC    OP OPERAND  asm                              A:.. X:.. Y:.. P:.. SP:.. PPU:r,c CYC:n

Usage: morning-me hand-examines this trace to identify what game
code runs during the divergence. Comparing PCs to a Zelda
disassembly (datacrystal/Zelda has one) names the routine, and the
register dump shows the CPU state going in / out of each
instruction. The first instruction whose A/X/Y/P diverges from
real-hardware behaviour is the bug location.

To get a comparable trace from a known-good emulator you'd need to
modify nes-py (or fceux/Mesen via subprocess) — out of scope here.
But this trace alone is useful: a 1500-line file of "what nes_core
ran" during 30 frames around the explosion lets the next agent /
human spot anomalies (recurring loops, suspicious PC ranges, NMI
re-entry patterns, etc.).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

import nes_core


ROM = REPO / "roms" / "Legend of Zelda, The (USA) (Rev A).nes"
TAPE = REPO / "roms" / "zelda_start_419.state.bin"
OUT = Path("/tmp/zelda_cave_trace.txt")

# How many frames around the explosion to trace at instruction
# resolution. Frame 1466 is the Start-press tick. We trace from a
# few frames before to ~30 frames after for context.
TRACE_FROM_FRAME = 1463
TRACE_TO_FRAME = 1500


def main() -> int:
    if not ROM.exists() or not TAPE.exists():
        print(f"missing inputs: {ROM} {TAPE}", file=sys.stderr)
        return 1

    env = nes_core.NESEnvironment(rom_path=str(ROM), frame_skip=1)
    env.reset()

    buttons = list(TAPE.read_bytes())
    print(f"replaying {TRACE_FROM_FRAME} frames to reach trace start", flush=True)
    for i in range(TRACE_FROM_FRAME):
        env.step(int(buttons[i]) & 0xFF)

    out = open(OUT, "w")
    out.write(f"# Per-instruction trace, frames {TRACE_FROM_FRAME}-{TRACE_TO_FRAME}\n")
    out.write(f"# Generated by tests/parity/zelda_cave_per_instruction_trace.py\n")
    out.write(f"# Pre-trace state: PC=0x{env.cpu_state()[0]:04X}\n\n")

    total_instructions = 0
    for f in range(TRACE_FROM_FRAME, TRACE_TO_FRAME):
        b = int(buttons[f]) & 0xFF
        out.write(f"\n=== frame {f} (button mask 0x{b:02X}) ===\n")
        env.set_buttons(b)
        # Step instruction-by-instruction until we've consumed a full
        # frame's worth of CPU cycles. NTSC NES = ~29830 CPU cycles/frame.
        # Cap iterations to detect runaway.
        cycles_in_frame = 0
        n_in_frame = 0
        TARGET = 29800
        while cycles_in_frame < TARGET:
            line = env.trace_line()
            out.write(line + "\n")
            _, _, ticks = env.step_one_instruction()
            cycles_in_frame += ticks
            n_in_frame += 1
            total_instructions += 1
            if n_in_frame > 10_000:
                out.write(f"# WARN runaway at frame {f}, breaking\n")
                break

    out.close()
    print(
        f"wrote {total_instructions} instruction lines to {OUT}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
