"""The ARMING DECISION gets a test, which is the gap 4dd15ea shipped through.

On 2026-08-26, 23 profiles were armed with `solve.clear.signals.scene_cut`
off a survey whose script was never committed. Every scene_cut test in the
suite that day drove a SYNTHETIC profile built by a local `_profile(...)`
helper, so nothing in code read the real `configs/*.yaml` and nothing could
have failed when:

  * four profiles armed `kind: [fade]` -- a blank-only gate -- on a blank
    counter measured at ZERO runs in 12,000 steps. `tetris_usa` was
    DECLINED on that exact evidence.
  * `darkwing_duck` armed `death_debounce: 3` over `lives: 0`, an admitted
    placeholder the survey itself recorded as `have_lives: false`, so the
    veto debounced RAM[0x0000].
  * `ninja_gaiden` armed the same veto over `lives: 0x001F`, which
    docs/research/FALSE_DEATH_FANOUT_2026-08-26.md measures the SAME DAY
    as a 0<->255 flicker artifact.
  * ten profiles armed `scene_min: 1`, which SceneCutSignal's own
    docstring forbids in writing.
  * seven profiles armed `blank_min: 1` while every blank run their own
    survey observed was a death fade 5-9 steps long -- the gate sat an
    order of magnitude BELOW its own null and the death veto was the
    only thing holding it shut. On `gradius` that veto was covering
    87.5% of every window, so its "residual 0" was a property of the
    veto and not of the gate at all.

WHAT THESE TESTS REPORT WHEN THE MECHANISM IS ABSENT (the binding
anti-vacuity question, answered in code):

  * `test_every_armed_profile_passes_every_clause` reads the REAL config
    files. If the arming policy were deleted -- every clause returning ok
    -- `test_the_policy_can_still_fail` fails, because it drives the same
    clauses over profiles constructed to violate each one and demands a
    refusal.
  * `test_the_committed_audit_covers_exactly_the_armed_set` fails if the
    receipt drifts from the configs in EITHER direction, so an arming
    added without re-running the audit is caught even though the test
    itself runs no emulator.
  * the residual assertions read `residual_triggers` from the audit
    receipt. A profile whose odometer is dead also reports 0 there, which
    is why C1 is a separate clause over the RAW run counts and is asserted
    separately -- a passing residual alone is never taken as health.

WHAT THE MEASUREMENT DECIDED (2026-08-27). Re-run as a measurement rather
than a judgement, the arming does not survive: **14 of the 23 armed gates
fire on play that cleared nothing**, up to 207 false positives on one
profile. All 23 are now disarmed with `enabled: false` and a per-profile
measured reason, and the cohort is back at quorum UNREACHABLE where it was
before 4dd15ea.

That creates a vacuity risk of its own, which is why there are two
receipts. With nothing armed, every residual assertion below iterates an
EMPTY set and passes for free. So the evidence the disarm rests on is
committed as well -- the same audit, same budget, same seed, run against
the 2026-08-26 arming before it was taken down -- and
`test_the_disarm_had_evidence_and_the_evidence_is_committed` fails rather
than skips if it goes missing.

None of this needs a ROM: the expensive half (`--audit`) is banked in
docs/receipts/clear_control/scene_cut_arming_2026-08-27.json (as shipped)
and scene_cut_arming_asfound_2026-08-27.json (as found), regenerated by
`scripts/scene_cut_arming.py --audit`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

from scripts import scene_cut_arming  # noqa: E402
from scripts.scene_cut_arming import (  # noqa: E402
    ASFOUND, FALSIFIED_LIVES, RECEIPT, SURVEY, adjudicate, armed_block, cohort,
    static_clauses,
)


def _survey() -> dict:
    if not SURVEY.exists():
        pytest.skip(f"survey receipt absent: {SURVEY}")
    return (json.loads(SURVEY.read_text()) or {}).get("survey") or {}


def _audit() -> dict:
    if not RECEIPT.exists():
        pytest.skip(f"arming receipt absent: {RECEIPT}")
    return (json.loads(RECEIPT.read_text()) or {}).get("profiles") or {}


def _armed_paths() -> list[Path]:
    return [p for p in cohort()
            if armed_block(yaml.safe_load(p.read_text())) is not None]


# ===========================================================================
# FIRST: the policy must be able to say no.
# ===========================================================================

def test_the_policy_can_still_fail() -> None:
    """Each clause, driven over a profile built to violate exactly it.

    This is the mutation harness in test form: replace any one clause's
    verdict with a constant True and the matching case below stops
    refusing. Without this test the roster assertions would pass just as
    happily over a policy that never refuses anything."""
    def prof(**over):
        cfg = {"scene_min": 6, "blank_min": 1, "kind": ["fade"],
               "death_debounce": 3}
        cfg.update(over.pop("cfg", {}))
        solve = {"progress": {"source": "odometer"}, "lives": 0x0100,
                 "clear": {"signals": {"scene_cut": cfg}}}
        solve.update(over)
        return {"solve": solve}

    live = {"n_blank_runs": 7, "n_scene_runs": 3,
            "has_non_death_candidate": True}

    def verdicts(name, p, sv, path=None):
        return {c["clause"]: c["ok"] for c in static_clauses(name, p, sv, path)}

    # C1 -- blank-only arm over a blank counter measured at zero.
    dead = dict(live, n_blank_runs=0)
    assert verdicts("x", prof(), dead)["C1_CHANNEL_ALIVE"] is False
    assert verdicts("x", prof(), live)["C1_CHANNEL_ALIVE"] is True
    # ...and a scene-gating arm survives a dead BLANK channel only because
    # its own channel moved, which is the asymmetry C1 has to get right.
    pan = prof(cfg={"kind": ["pan", "warp", "fade"]})
    assert verdicts("x", pan, dead)["C1_CHANNEL_ALIVE"] is True

    # C2 -- no lives byte at all, and a measured-false one.
    assert verdicts("x", prof(lives=0), live)["C2_VALIDATED_LIVES"] is False
    assert verdicts("x", prof(lives=None), live)["C2_VALIDATED_LIVES"] is False
    name, addr = next(iter(FALSIFIED_LIVES))
    assert verdicts(name, prof(lives=addr), live)["C2_VALIDATED_LIVES"] is False
    # ...the SAME address on a different profile is not condemned: the
    # falsification is a measurement about one game's byte, not a global
    # blacklist of an integer.
    assert verdicts("other", prof(lives=addr), live)["C2_VALIDATED_LIVES"] is True
    # ...and no veto declared means nothing to validate.
    novet = prof(lives=0, cfg={"death_debounce": None})
    novet["solve"]["clear"]["signals"]["scene_cut"].pop("death_debounce")
    assert verdicts("x", novet, live)["C2_VALIDATED_LIVES"] is True

    # C3 -- an all-death-class population with no disclosure in the file.
    deathonly = dict(live, has_non_death_candidate=False)
    v = verdicts("x", prof(), deathonly, None)
    assert v["C3_SEPARABILITY_DISCLOSED"] is False
    assert "C3_SEPARABILITY_DISCLOSED" not in verdicts("x", prof(), live)

    # C5 -- the seam floor.
    assert verdicts("x", prof(cfg={"scene_min": 1}),
                    live)["C5_SCENE_MIN_ABOVE_SEAM"] is False
    assert verdicts("x", prof(cfg={"scene_min": 2}),
                    live)["C5_SCENE_MIN_ABOVE_SEAM"] is True

    # C6 -- the gate against the VETO-INDEPENDENT null. This is the
    # gradius shape: a blank_min of 1 under a measured null of 36, whose
    # residual reads 0 only because the death veto covered the windows
    # that would have fired.
    def c6(cfg, banked):
        return {c["clause"]: c["ok"] for c in
                static_clauses("x", prof(cfg=cfg), live, None,
                               banked=banked)}["C6_GATE_ABOVE_FULL_NULL"]

    null36 = {"null_max_d_blank_all": 36, "null_max_d_scene_all": 0,
              "null_max_d_blank": 0, "null_max_d_scene": 0,
              "n_rollouts": 4, "steps_per_rollout": 6000}
    assert c6({"blank_min": 1}, null36) is False, (
        "a gate under its own null must be refused even when the vetoed-out "
        "null reads 0 -- that zero is the veto's number, not the gate's")
    assert c6({"blank_min": 37}, null36) is True
    assert c6({"blank_min": 36}, null36) is False, "at the null is not above it"
    # ...and the scene half of the same clause.
    assert c6({"scene_min": 6, "blank_min": 37},
              dict(null36, null_max_d_scene_all=6)) is False
    # A missing measurement is not a passing one, exactly as with C1.
    assert c6({"blank_min": 999}, None) is False


def test_a_missing_survey_record_is_not_a_passing_one() -> None:
    """A profile nobody measured must not sail through C1. `ok: False`
    with a reason, never a silent skip -- the same rule the campaign's
    UNINSTRUMENTED/UNAVAILABLE verdicts follow."""
    p = {"solve": {"progress": {"source": "odometer"}, "lives": 0x100,
                   "clear": {"signals": {"scene_cut": {
                       "scene_min": 6, "blank_min": 1, "kind": ["fade"],
                       "death_debounce": 3}}}}}
    c = {x["clause"]: x for x in static_clauses("nobody", p, None)}
    assert c["C1_CHANNEL_ALIVE"]["ok"] is False
    assert "never been measured" in c["C1_CHANNEL_ALIVE"]["detail"]


# ===========================================================================
# The roster, read off the real files.
# ===========================================================================

def test_the_cohort_is_derived_and_non_empty() -> None:
    names = [p.stem for p in cohort()]
    assert len(names) >= 20, names
    assert "rygar" in names and "tetris_usa" in names


def test_every_armed_profile_passes_every_clause() -> None:
    """The roster fact 4dd15ea had no test for."""
    survey = _survey()
    # NOT `_audit()`: that skips when the receipt is absent, and a skip
    # here would mean an arming with no measurement behind it sails
    # through. An absent receipt makes C6 report `ok: False` with a
    # reason, which is the same rule C1 follows for an absent survey
    # record -- a missing measurement is not a passing one.
    audit = ((json.loads(RECEIPT.read_text()) or {}).get("profiles") or {}
             ) if RECEIPT.exists() else {}
    bad = {}
    for p in _armed_paths():
        prof = yaml.safe_load(p.read_text())
        banked = (audit.get(p.stem) or {}).get("measured")
        failed = [c for c in static_clauses(p.stem, prof, survey.get(p.stem), p,
                                            banked=banked)
                  if not c["ok"]]
        if failed:
            bad[p.stem] = [(c["clause"], c["detail"]) for c in failed]
    assert not bad, (
        "these profiles arm scene_cut against their own recorded evidence:\n"
        + json.dumps(bad, indent=1))


def test_no_armed_profile_declares_a_falsified_lives_byte() -> None:
    """Stated separately from C2 so the list itself is exercised: adding a
    newly-falsified byte to FALSIFIED_LIVES must disarm every veto reading
    it, and this is the test that would go red when it does."""
    for p in _armed_paths():
        prof = yaml.safe_load(p.read_text())
        addr = (prof.get("solve") or {}).get("lives")
        if addr and "death_debounce" in (armed_block(prof) or {}):
            assert (p.stem, int(addr)) not in FALSIFIED_LIVES, p.stem


def test_a_death_veto_requires_a_lives_byte_that_exists() -> None:
    for p in _armed_paths():
        prof = yaml.safe_load(p.read_text())
        cfg = armed_block(prof) or {}
        if "death_debounce" in cfg:
            addr = (prof.get("solve") or {}).get("lives")
            assert addr, (
                f"{p.stem} arms death_debounce={cfg['death_debounce']} over "
                f"solve.lives={addr!r}; GenericGame.lives is int(ram[addr]) "
                "with no None handling, so the veto would debounce "
                "RAM[0x0000]")


# ===========================================================================
# The banked audit: the measured half, asserted without an emulator.
# ===========================================================================

def test_the_committed_audit_covers_exactly_the_armed_set() -> None:
    """Drift in EITHER direction is a failure: a profile armed without
    re-running the audit, or an audit row for a profile since disarmed."""
    rows = _audit()
    armed_in_receipt = {n for n, r in rows.items()
                        if (r.get("measured") or {}).get("armed")}
    armed_on_disk = {p.stem for p in _armed_paths()}
    assert armed_in_receipt == armed_on_disk, {
        "in receipt only": sorted(armed_in_receipt - armed_on_disk),
        "on disk only": sorted(armed_on_disk - armed_in_receipt)}


def test_no_armed_gate_fires_on_play_that_cleared_nothing() -> None:
    """C4, the anti-vacuity measurement. The audit drives each profile's
    OWN armed signal over mixed-random play that reaches no level
    transition, so every trigger is a false positive."""
    rows = _audit()
    fired = {n: r["measured"]["residual_triggers"]
             for n, r in rows.items()
             if (r.get("measured") or {}).get("armed")
             and r["measured"].get("residual_triggers")}
    assert not fired, (
        "armed scene_cut gates firing on ordinary play: " + json.dumps(fired))


def test_the_audit_records_a_live_channel_for_every_armed_profile() -> None:
    """The other half of the pair above, and the reason a 0 residual is
    never read as health on its own: a dead odometer also scores 0."""
    rows = _audit()
    for n, r in rows.items():
        m = r.get("measured") or {}
        if not m.get("armed"):
            continue
        kind = set((m.get("gate") or {}).get("kind") or ())
        live = m["n_blank_runs"] + (m["n_scene_runs"]
                                    if kind & {"pan", "warp"} else 0)
        assert live > 0, (
            f"{n} is armed on a channel the audit measured at zero runs -- "
            "the evidence state tetris_usa was declined for")


def test_an_armed_gate_is_never_below_its_own_measured_null() -> None:
    """The rule scripts/clear_calibrate.py already applies, enforced on
    the roster: the gate must be at least one integer above what ordinary
    play produces on the channel it reads."""
    rows = _audit()
    bad = {}
    for n, r in rows.items():
        m = r.get("measured") or {}
        g = m.get("gate")
        if not g:
            continue
        if int(g["blank_min"]) <= int(m["null_max_d_blank"]):
            bad[n] = f"blank_min={g['blank_min']} <= null {m['null_max_d_blank']}"
        if int(g["scene_min"]) <= int(m["null_max_d_scene"]):
            bad[n] = f"scene_min={g['scene_min']} <= null {m['null_max_d_scene']}"
    assert not bad, json.dumps(bad, indent=1)


def test_an_armed_gate_clears_its_veto_INDEPENDENT_null() -> None:
    """C6 on the roster, and the one the test above is NOT a substitute
    for.

    `null_max_d_blank` excludes every window the death veto covered, so a
    gate can read "above its null" while sitting an order of magnitude
    under the death fades that null was computed by deleting. That is the
    shape `gradius` shipped in: `blank_min: 1` against a vetoed-out null
    of 0 and a veto covering 87.5% of all windows.

    The probe that produced these numbers cleared nothing, so its ENTIRE
    (d_scene, d_blank) distribution is null and the gate has to clear the
    whole of it on its own. The death veto is then a second guard rather
    than the only one -- which is the difference between a defence and a
    single point of failure."""
    rows = _audit()
    bad = {}
    for n, r in rows.items():
        m = r.get("measured") or {}
        g = m.get("gate")
        if not g:
            continue
        assert "null_max_d_blank_all" in m, (
            f"{n}: the receipt carries no veto-independent null, so C6 "
            "cannot be evaluated and must not be assumed")
        if int(g["blank_min"]) <= int(m["null_max_d_blank_all"]):
            bad[n] = (f"blank_min={g['blank_min']} <= veto-independent null "
                      f"{m['null_max_d_blank_all']}")
        elif int(g["scene_min"]) <= int(m["null_max_d_scene_all"]):
            bad[n] = (f"scene_min={g['scene_min']} <= veto-independent null "
                      f"{m['null_max_d_scene_all']}")
    assert not bad, json.dumps(bad, indent=1)


def test_the_disarm_had_evidence_and_the_evidence_is_committed() -> None:
    """THE ANTI-VACUITY TEST FOR THE DISARM ITSELF.

    After this commit no cohort profile arms `scene_cut`, so every
    residual assertion above iterates an EMPTY set and passes for free.
    That is exactly the shape this campaign is named after, so the
    evidence the decision rested on is committed too: the same audit, at
    the same budget and seed, run against the 2026-08-26 arming before it
    was taken down.

    What this reports if the mechanism is absent: a missing or empty
    as-found receipt fails here rather than skipping, because "we disarmed
    23 profiles" with no measurement behind it is a judgement wearing a
    measurement's clothes -- which is the exact criticism that produced
    this commit."""
    assert ASFOUND.exists(), (
        f"the as-found measurement is missing: {ASFOUND}. The disarm of 23 "
        "profiles has no committed evidence, so nothing distinguishes it "
        "from giving up")
    rows = (json.loads(ASFOUND.read_text()) or {}).get("profiles") or {}
    armed = {n: r["measured"] for n, r in rows.items()
             if (r.get("measured") or {}).get("armed")}
    assert len(armed) == 23, (
        f"the as-found receipt describes {len(armed)} armed profiles; "
        "4dd15ea armed 23")
    firing = {n: m["residual_triggers"] for n, m in armed.items()
              if m.get("residual_triggers")}
    assert len(firing) >= 10, (
        "the as-found receipt no longer shows the armed gates firing on "
        "non-clearing play, which is the finding the disarm rests on: "
        + json.dumps(firing))
    # ...and the refusals must not depend on the veto-independent null
    # being the number used: every firing gate is also at or below its
    # WEAKER, vetoed-out null, so C6's verdict here is robust to which
    # null you pick.
    fragile = {n: (armed[n]["gate"]["blank_min"],
                   armed[n]["null_max_d_blank"],
                   armed[n]["null_max_d_blank_all"])
               for n in firing
               if armed[n]["gate"]["blank_min"] > armed[n]["null_max_d_blank"]}
    assert not fragile, (
        "some firing gate clears the vetoed-out null and is refused only by "
        "the veto-independent one -- report that rather than asserting it "
        "away: " + json.dumps(fragile))


def test_the_two_nulls_hold_their_invariant_and_the_veto_shaves_almost_nothing() -> None:
    """What the veto's coverage is actually worth, measured.

    `null_max_d_blank_all` counts every window; `null_max_d_blank` drops
    the ones the death veto covered. The first can never be SMALLER --
    that is a structural invariant of NullTracker and a violation means
    the tracker is miscounting, not that the roster changed.

    The measured finding underneath it: on the blank channel -- the
    channel every one of these gates actually votes with -- the veto
    barely moves the number, because SceneCutSignal's window is 240
    observations while the veto's transient is a handful. A fade's blank
    movement is still inside the rolling buffer long after `dying` has
    cleared and lands in a non-vetoed window anyway. So "the debounced
    death veto is what keeps this armed signal from mistaking a respawn
    for a transition", the sentence six 2026-08-26 configs shipped, was
    not true of the blank channel.

    Whether that shave ever changes an arming verdict is asserted
    separately, by the `fragile` check in
    `test_the_disarm_had_evidence_and_the_evidence_is_committed`."""
    if not ASFOUND.exists():
        pytest.skip(f"as-found receipt absent: {ASFOUND}")
    rows = (json.loads(ASFOUND.read_text()) or {}).get("profiles") or {}
    seen = 0
    for n, r in rows.items():
        m = r.get("measured") or {}
        if m.get("unmeasurable") or m.get("n_blank_runs") is None:
            continue
        seen += 1
        assert m["null_max_d_blank_all"] >= m["null_max_d_blank"], (
            f"{n}: the veto-independent null is SMALLER than the vetoed-out "
            "one, which is impossible -- NullTracker is miscounting")
        assert m["null_max_d_scene_all"] >= m["null_max_d_scene"], n
    assert seen >= 20, f"only {seen} profiles carry a null measurement"


def test_c6_catches_at_least_one_gate_the_older_null_rule_would_pass() -> None:
    """C6 EARNS ITS PLACE ON THE REAL ROSTER, not only on a fixture.

    `test_the_policy_can_still_fail` proves C6 refuses a synthetic gate
    under a synthetic null. That is necessary and not sufficient: a clause
    that never separates from the clause it supersedes is decoration. So
    this demands a REAL profile in the as-found receipt that

        passes the older rule  (gate > vetoed-out null), and
        fails C6              (gate <= veto-independent null)

    -- i.e. a gate whose residual reads 0 only because the death veto
    covered every window that would have fired it. `megaman` is that case:
    vetoed-out null (0, 0), veto-independent null (2, 18), gate
    blank_min 1, residual 0. If no such profile exists the two rules agree
    everywhere and C6 should be reported as inert rather than kept as if
    it were load-bearing."""
    if not ASFOUND.exists():
        pytest.skip(f"as-found receipt absent: {ASFOUND}")
    rows = (json.loads(ASFOUND.read_text()) or {}).get("profiles") or {}
    separated = {}
    for n, r in rows.items():
        m = r.get("measured") or {}
        g = m.get("gate")
        if not g or m.get("unmeasurable"):
            continue
        old_ok = (int(g["blank_min"]) > int(m["null_max_d_blank"])
                  and int(g["scene_min"]) > int(m["null_max_d_scene"]))
        new_ok = (int(g["blank_min"]) > int(m["null_max_d_blank_all"])
                  and int(g["scene_min"]) > int(m["null_max_d_scene_all"]))
        if old_ok and not new_ok:
            separated[n] = {"gate": g,
                            "null_vetoed": [m["null_max_d_scene"],
                                            m["null_max_d_blank"]],
                            "null_all": [m["null_max_d_scene_all"],
                                         m["null_max_d_blank_all"]],
                            "residual": m["residual_triggers"]}
    assert separated, (
        "no armed gate on the real roster is refused by C6 while passing the "
        "vetoed-out null rule -- on this data C6 is inert and must be "
        "reported as such, not carried as a load-bearing clause")


def test_a_veto_that_covered_every_check_would_be_reported() -> None:
    """LIVENESS. A death veto that never releases is exactly as vacuous as
    a gate that always fires, and the receipt has to carry the number that
    would show it."""
    rows = _audit()
    for n, r in rows.items():
        m = r.get("measured") or {}
        if not m.get("armed"):
            continue
        assert "fraction_checks_vetoed" in m, n
        assert m["rollouts_ending_dying"] == 0, (
            f"{n}: {m['rollouts_ending_dying']} of {m['n_rollouts']} rollouts "
            "ended with the death veto still latched -- the signal cannot "
            "vote from there to the end of the episode")


def test_adjudicate_declines_on_a_nonzero_residual(monkeypatch) -> None:
    """The measured clause has to be able to refuse too, not only the
    static ones.

    A witnessed transition is registered for the synthetic profile so C7
    is not what is doing the refusing -- otherwise this test would pass
    for the wrong reason and stop being about the residual at all."""
    monkeypatch.setitem(scene_cut_arming.WITNESSED_TRANSITIONS, "x",
                        "synthetic fixture: a witnessed transition")
    prof = {"solve": {"progress": {"source": "odometer"}, "lives": 0x100,
                      "clear": {"signals": {"scene_cut": {
                          "scene_min": 6, "blank_min": 40, "kind": ["fade"],
                          "death_debounce": 3}}}}}
    sv = {"n_blank_runs": 4, "n_scene_runs": 0,
          "has_non_death_candidate": True}
    base = {"n_rollouts": 3, "steps_per_rollout": 4000,
            "null_max_d_blank_all": 12, "null_max_d_scene_all": 2,
            "null_max_d_blank": 12, "null_max_d_scene": 2}
    clean = adjudicate("x", Path("configs/x.yaml"), prof, sv,
                       dict(base, residual_triggers=0,
                            recommended_gate={"scene_min": 3,
                                              "blank_min": 13}))
    assert clean["verdict"] == "ARM", clean
    dirty = adjudicate("x", Path("configs/x.yaml"), prof, sv,
                       dict(base, residual_triggers=12,
                            recommended_gate={"scene_min": 3,
                                              "blank_min": 13}))
    assert dirty["verdict"] == "DECLINE"
    assert "C4_RESIDUAL_ZERO" in dirty["blocking"]

    # ...and the unmeasurable case is a refusal too, not a pass. A profile
    # that cannot be driven (tetris_usa: `solve.constructible: false`)
    # would otherwise arrive with residual None and read as clean.
    dead = adjudicate("x", Path("configs/x.yaml"), prof, sv,
                      dict(base, residual_triggers=None,
                           unmeasurable="ProfileNotConstructible: ...",
                           recommended_gate=None))
    assert dead["verdict"] == "DECLINE"
    assert "C4_UNMEASURABLE" in dead["blocking"]


def test_c7_is_what_refuses_the_roster_and_it_can_be_satisfied(monkeypatch) -> None:
    """C7 must be a clause, not a wall.

    The whole cohort is declined on C7 today, so this test pins BOTH
    directions: that C7 is genuinely what refuses (not an accident of
    another clause), and that registering a witnessed transition lifts
    it. Without the second half, "everything is declined" would be
    indistinguishable from a policy that can never say yes -- which is
    the vacuity this campaign is named after, pointed the other way."""
    prof = {"solve": {"progress": {"source": "odometer"}, "lives": 0x100,
                      "clear": {"signals": {"scene_cut": {
                          "scene_min": 6, "blank_min": 40, "kind": ["fade"],
                          "death_debounce": 3}}}}}
    sv = {"n_blank_runs": 4, "n_scene_runs": 0,
          "has_non_death_candidate": True}
    banked = {"n_rollouts": 3, "steps_per_rollout": 4000,
              "null_max_d_blank_all": 12, "null_max_d_scene_all": 2,
              "null_max_d_blank": 12, "null_max_d_scene": 2,
              "residual_triggers": 0,
              "recommended_gate": {"scene_min": 3, "blank_min": 13}}

    def verdict():
        return {c["clause"]: c["ok"] for c in
                static_clauses("x", prof, sv, None, banked=banked)}

    assert verdict()["C7_SEPARABILITY_WITNESSED"] is False
    monkeypatch.setitem(scene_cut_arming.WITNESSED_TRANSITIONS, "x",
                        "synthetic fixture: a witnessed transition")
    assert verdict()["C7_SEPARABILITY_WITNESSED"] is True
    # ...and with C7 satisfied every other clause on this fixture passes,
    # so C7 really was the only thing refusing it.
    assert all(verdict().values()), verdict()


def test_the_whole_cohort_is_declined_and_every_refusal_names_its_numbers() -> None:
    """The roster fact this commit actually ships.

    Every cohort profile that carried the 2026-08-26 arming must now be
    disarmed, and each refusal must carry that profile's OWN measurement
    -- not a shared sentence. A blanket disarm with one boilerplate reason
    would be indistinguishable from giving up."""
    reasons, roms = {}, {}
    for p in cohort():
        prof = yaml.safe_load(p.read_text())
        blk = ((((prof.get("solve") or {}).get("clear") or {})
                .get("signals") or {}).get("scene_cut") or {})
        if blk.get("enabled") is False:
            reasons[p.stem] = blk.get("reason") or ""
            roms[p.stem] = (prof.get("solve") or {}).get("rom")
    assert len(reasons) >= 23, (
        f"only {len(reasons)} profiles carry an explicit scene_cut refusal; "
        "the 2026-08-26 arming covered 23")

    # Two profiles may share a refusal ONLY when they are two profiles of
    # the same ROM measured identically -- `metroid` and `metroid_roomfp`
    # are that case and an identical measurement earning an identical
    # sentence is correct. Any other repeat is boilerplate.
    by_reason: dict[str, list[str]] = {}
    for n, r in reasons.items():
        by_reason.setdefault(r, []).append(n)
    shared = {r: ns for r, ns in by_reason.items() if len(ns) > 1}
    for r, ns in shared.items():
        assert len({roms[n] for n in ns}) == 1, (
            f"{sorted(ns)} share a refusal reason verbatim but are different "
            "games -- a refusal that is not about the profile is not a "
            "measurement")
    assert len(by_reason) >= len(reasons) - 1, (
        f"{len(reasons)} refusals collapse to only {len(by_reason)} distinct "
        "sentences")

    for n, r in reasons.items():
        assert "scene_cut_arming.py" in r, n
        assert any(ch.isdigit() for ch in r), (
            f"{n}: refusal carries no number at all")
        # ...and the numbers must be THIS profile's own blank-channel
        # measurement -- the channel the refusal is about. Every refusal
        # quotes either the gate it is refusing, that gate's null, or the
        # run count that made the channel dead.
        assert any(k in r for k in ("blank_min=", "max d_blank=",
                                    "odo_blank produced")), n


def test_a_disarmed_profile_reads_as_declined_not_as_absent() -> None:
    """`enabled: false` is a refusal WITH a reason and must be visible as
    one -- a profile disarmed by deleting the block would leave no record
    of why."""
    disarmed = [p for p in cohort()
                if ((((yaml.safe_load(p.read_text()).get("solve") or {})
                      .get("clear") or {}).get("signals") or {})
                    .get("scene_cut", {}) or {}).get("enabled") is False]
    for p in disarmed:
        blk = ((((yaml.safe_load(p.read_text()).get("solve") or {})
                 .get("clear") or {}).get("signals") or {})["scene_cut"])
        assert blk.get("reason"), (
            f"{p.stem} declines scene_cut with no reason recorded")
        assert armed_block(yaml.safe_load(p.read_text())) is None
